-- .luacheckrc
std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "212/self", "611", "612", "613", "614", "621" } -- implicit self (house ns: methods) + whitespace — StyLua owns the latter
exclude_files = {
	"Includes/", -- vendored, never linted
	-- Dev-only offline suites, in both homes. They stub the WoW globals this
	-- config protects, so linting them reports every stub as a violation.
	"Features/Restocker/Tests/",
	"Features/Tests/",
}
read_globals = {
	-- WoW API surface Connoisseur calls
	"BACKPACK_CONTAINER",
	"BANK_CONTAINER",
	"bit",
	"BuyMerchantItem",
	"C_AddOns",
	"C_Container",
	"C_EventUtils",
	"C_Item",
	"C_Map",
	"C_Timer",
	"C_UnitAuras",
	"ClearCursor",
	"CopyTable",
	"CreateFrame",
	"CreateMacro",
	"CursorHasItem",
	"DeleteMacro",
	"EditMacro",
	"ERR_BANK_FULL",
	"ERR_INV_FULL",
	"ERR_ITEM_WRONG_ZONE",
	"format",
	"GameTooltip",
	"GetBuildInfo",
	"GetCursorInfo",
	"GetCVar",
	"GetInventoryItemDurability",
	"GetInventoryItemLink",
	"GetItemCount",
	"GetItemFamily",
	"GetItemIcon",
	"GetItemInfo",
	"GetItemQualityColor",
	"GetLocale",
	"GetMacroBody",
	"GetMacroIndexByName",
	"GetMerchantItemInfo",
	"GetMerchantItemLink",
	"GetMerchantNumItems",
	"GetNetStats",
	"GetNumGroupMembers",
	"GetNumMacros",
	"GetNumQuestLogEntries",
	"GetNumSkillLines",
	"GetNumTalentTabs",
	"GetPetFoodTypes",
	"GetPhysicalScreenSize",
	"GetQuestLogTitle",
	"GetRealmName",
	"GetSkillLineInfo",
	"GetSpellInfo",
	"GetSubZoneText",
	"GetTalentTabInfo",
	"GetTime",
	"GetWeaponEnchantInfo",
	"GetZoneText",
	"InCombatLockdown",
	"IsInGroup",
	"IsInInstance",
	"IsInRaid",
	"IsPlayerSpell",
	"IsResting",
	"IsShiftKeyDown",
	"IsSpellKnown",
	"ITEM_QUALITY_COLORS",
	"LibStub",
	"MacroFrame",
	"MAX_ACCOUNT_MACROS",
	"NO",
	"NUM_BAG_SLOTS",
	"PlaySound",
	"PlaySoundFile",
	"RAID_CLASS_COLORS",
	"SecureCmdOptionParse",
	"SetCVar",
	"Settings",
	"SOUNDKIT",
	"SPELL_FAILED_TARGETS_DEAD",
	"StaticPopup_Show",
	"strsplit",
	"strtrim",
	"tinsert",
	"UIParent",
	"UISpecialFrames",
	"UnitCharacterPoints",
	"UnitClass",
	"UnitExists",
	"UnitIsDead",
	"UnitIsFriend",
	"UnitIsGhost",
	"UnitIsPlayer",
	"UnitIsPVP",
	"UnitIsUnit",
	"UnitLevel",
	"UnitName",
	"UnitOnTaxi",
	"UnitRace",
	"UnitReaction",
	"wipe",
	"WOW_PROJECT_BURNING_CRUSADE_CLASSIC",
	"WOW_PROJECT_CLASSIC",
	"WOW_PROJECT_ID",
	"YES",
}
globals = {
	-- the add-on's own sanctioned globals
	"ConnoisseurDB",
	-- Read once at login and cleared; see Features/Restocker/Restocker-Saved-Migration.lua
	"ConnoisseurRestockerDB",
	"ConnoisseurState",
	"ConnFire",
	"ConnTip",
	"ConnIf",
	"ConnNoItem",
	"SLASH_CONNOISSEUR1",
	"SLASH_CONNOISSEURRESTOCKER1",
	"SlashCmdList",
}
