-- .luacheckrc
std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "611", "612", "613", "614", "621" } -- whitespace warnings — StyLua owns these too
self = false -- colon-defined handlers and widget stubs legitimately ignore self
exclude_files = {
	"Includes/", -- vendored, never linted
	"Features/Restocker/", -- vendored shape per References/Exceptions.md; converges in its own scheduled pass
}
read_globals = {
	-- WoW API surface Connoisseur calls
	"BuyMerchantItem",
	"C_AddOns",
	"C_Container",
	"C_EventUtils",
	"C_Item",
	"C_Map",
	"C_Timer",
	"CreateFrame",
	"CreateMacro",
	"DeleteMacro",
	"ERR_BANK_FULL",
	"ERR_INV_FULL",
	"ERR_ITEM_WRONG_ZONE",
	"EditMacro",
	"GameTooltip",
	"GetBuildInfo",
	"GetCVar",
	"GetContainerNumSlots",
	"GetInventorySlotInfo",
	"GetItemCount",
	"GetItemFamily",
	"GetItemIcon",
	"GetItemInfo",
	"GetItemQualityColor",
	"GetLocale",
	"GetMacroBody",
	"GetMacroIndexByName",
	"GetMerchantItemInfo",
	"GetMerchantItemLink",
	"GetMerchantNumItems",
	"GetNetStats",
	"GetNumGroupMembers",
	"GetNumMacros",
	"GetNumQuestLogEntries",
	"GetNumSkillLines",
	"GetPetFoodTypes",
	"GetPhysicalScreenSize",
	"GetQuestLogTitle",
	"GetSkillLineInfo",
	"GetSpellInfo",
	"GetSubZoneText",
	"GetTime",
	"GetZoneText",
	"InCombatLockdown",
	"IsInGroup",
	"IsInInstance",
	"IsInRaid",
	"IsPlayerSpell",
	"IsResting",
	"IsShiftKeyDown",
	"IsSpellKnown",
	"LibStub",
	"MAX_ACCOUNT_MACROS",
	"MacroFrame",
	"NUM_BAG_SLOTS",
	"PlaySound",
	"PlaySoundFile",
	"RAID_CLASS_COLORS",
	"SOUNDKIT",
	"SPELL_FAILED_TARGETS_DEAD",
	"SecureCmdOptionParse",
	"SetCVar",
	"Settings",
	"UIParent",
	"UISpecialFrames",
	"UnitAura",
	"UnitClass",
	"UnitExists",
	"UnitIsDead",
	"UnitIsFriend",
	"UnitIsGhost",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitLevel",
	"UnitOnTaxi",
	"UnitRace",
	"UnitReaction",
	"WOW_PROJECT_BURNING_CRUSADE_CLASSIC",
	"WOW_PROJECT_CLASSIC",
	"WOW_PROJECT_ID",
	"format",
	"tinsert",
	"wipe",
}
globals = {
	-- the add-on's own sanctioned globals
	"ConnoisseurDB",
	"ConnoisseurRestockerDB",
	"ConnoisseurState",
	"ConnFire",
	"ConnTip",
	"ConnIf",
	"ConnNoItem",
	"CRS_ADDON",
	"CrsModule",
	"CrsKvModuleManager",
	"SLASH_CONNOISSEUR1",
	"SLASH_CONNOISSEURRESTOCKER1",
	"SlashCmdList",
	"ChatEdit_InsertLink", -- Restocker's shift-click capture deliberately replaces-and-chains it
}
